export enum AppRoutesConstants {
    BET_DETAIL = '/bet',
    BET_DETAIL_PAGE = '/bet/:betId',
    ENGLISHLEAGUE_PAGE = '/englishleaguedetails',
    EVENTS_PAGE = '/events',
    FAVORITE = '/favorites',
    HOGWARTSCUP_PAGE = '/hogwartscupdetails',
    LOGIN_PAGE = '/login',
    MAIN_PAGE = '/',
    MATCHES_PAGE = '/matches',
    MATCH_DETAIL = '/match/:matchId',
    PROFILE = '/profile',
    RECHARGE = '/recharge-account',
    RECOVER_ACCOUNT_PAGE = '/recover-password',
    RESULTS_PAGE = '/results',
    SIGNUP_PAGE = '/signup',
    TEAMS_PAGE = '/teams',
    WORLDCUP_PAGE = '/worldcupdetails',
}
