export enum AppRoutesConstants {
    BET_DETAIL = '/bet/:betId',
    EVENTS_PAGE = '/events',
    FAVORITE = '/favorites',
    LOGIN_PAGE = '/login',
    MAIN_PAGE = '/',
    MATCHES_PAGE = '/matches',
    MATCH_DETAIL = '/match/:matchId',
    PROFILE = '/profile',
    RECHARGE = '/recharge-account',
    RECOVER_ACCOUNT_PAGE = '/recover-password',
    RESULTS_PAGE = '/results',
    SIGNUP_PAGE = '/signup',
    TEAMS_PAGE = '/teams',
}
